name = "bipathposets"
uuid = "6552261a-8a68-4950-8df9-178e3747c440"
authors = ["Shunsuke Tada"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
